CREATE TABLE IF NOT EXISTS `feedback_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conversation_id` INT NOT NULL,
  `message_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `feedback_type` VARCHAR(32) NOT NULL,
  `rating` INT NULL,
  `comment` TEXT NULL,
  `created_at` DATETIME NULL,
  `query_snapshot` MEDIUMTEXT NULL,
  `answer_snapshot` MEDIUMTEXT NULL,
  `retrieved_documents` MEDIUMTEXT NULL,
  `cited_documents` MEDIUMTEXT NULL,
  `trace_id` INT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_feedback_records_conversation_message_user_type` (`conversation_id`, `message_id`, `user_id`, `feedback_type`),
  KEY `idx_feedback_records_conversation_id` (`conversation_id`),
  KEY `idx_feedback_records_message_id` (`message_id`),
  KEY `idx_feedback_records_user_id` (`user_id`),
  KEY `idx_feedback_records_trace_id` (`trace_id`),
  KEY `idx_feedback_records_type` (`feedback_type`),
  KEY `idx_feedback_records_status` (`status`),
  KEY `idx_feedback_records_created_at` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `feedback_claims` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback_id` INT NOT NULL,
  `claim_type` VARCHAR(64) NOT NULL,
  `subject` VARCHAR(255) NULL,
  `predicate` VARCHAR(128) NULL,
  `object` TEXT NULL,
  `scope` VARCHAR(255) NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'user',
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `verification_status` VARCHAR(32) NOT NULL DEFAULT 'unverified',
  `evidence_ids` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_claims_feedback_id` (`feedback_id`),
  KEY `idx_feedback_claims_claim_type` (`claim_type`),
  KEY `idx_feedback_claims_subject` (`subject`),
  KEY `idx_feedback_claims_predicate` (`predicate`),
  KEY `idx_feedback_claims_scope` (`scope`),
  KEY `idx_feedback_claims_source` (`source`),
  KEY `idx_feedback_claims_verification_status` (`verification_status`),
  KEY `idx_feedback_claims_created_at` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `feedback_evidence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback_claim_id` INT NOT NULL,
  `evidence_type` VARCHAR(64) NOT NULL,
  `source_id` VARCHAR(255) NULL,
  `content` MEDIUMTEXT NULL,
  `relevance_score` FLOAT NOT NULL DEFAULT 0,
  `support_score` FLOAT NOT NULL DEFAULT 0,
  `contradiction_score` FLOAT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_evidence_claim_id` (`feedback_claim_id`),
  KEY `idx_feedback_evidence_type` (`evidence_type`),
  KEY `idx_feedback_evidence_source_id` (`source_id`),
  KEY `idx_feedback_evidence_created_at` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `feedback_verifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback_id` INT NOT NULL,
  `verifier_type` VARCHAR(32) NOT NULL,
  `verification_result` VARCHAR(32) NOT NULL,
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `reason` TEXT NULL,
  `evidence_summary` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_verifications_feedback_id` (`feedback_id`),
  KEY `idx_feedback_verifications_verifier_type` (`verifier_type`),
  KEY `idx_feedback_verifications_result` (`verification_result`),
  KEY `idx_feedback_verifications_created_at` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `user_reliability` (
  `user_id` INT NOT NULL,
  `total_feedback` INT NOT NULL DEFAULT 0,
  `verified_feedback` INT NOT NULL DEFAULT 0,
  `rejected_feedback` INT NOT NULL DEFAULT 0,
  `correction_feedback` INT NOT NULL DEFAULT 0,
  `correct_correction_count` INT NOT NULL DEFAULT 0,
  `reliability_score` FLOAT NOT NULL DEFAULT 0.5,
  `decay_factor` FLOAT NOT NULL DEFAULT 0.98,
  `recent_verified_weight` FLOAT NOT NULL DEFAULT 0,
  `recent_rejected_weight` FLOAT NOT NULL DEFAULT 0,
  `recent_correction_weight` FLOAT NOT NULL DEFAULT 0,
  `last_updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  KEY `idx_user_reliability_score` (`reliability_score`),
  KEY `idx_user_reliability_last_updated` (`last_updated_at`)
);

CREATE TABLE IF NOT EXISTS `fault_case_memory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `case_key` VARCHAR(255) NOT NULL,
  `device` VARCHAR(255) NULL,
  `device_type` VARCHAR(255) NULL,
  `component` VARCHAR(255) NULL,
  `firmware_version` VARCHAR(128) NULL,
  `symptoms` MEDIUMTEXT NULL,
  `metrics` MEDIUMTEXT NULL,
  `alarm_codes` MEDIUMTEXT NULL,
  `confirmed_fault` TEXT NULL,
  `root_cause` TEXT NULL,
  `actions` MEDIUMTEXT NULL,
  `outcome` TEXT NULL,
  `evidence_ids` MEDIUMTEXT NULL,
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `verification_status` VARCHAR(32) NOT NULL DEFAULT 'candidate',
  `source_feedback_ids` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_fault_case_memory_case_key` (`case_key`),
  KEY `idx_fault_case_memory_device` (`device`),
  KEY `idx_fault_case_memory_device_type` (`device_type`),
  KEY `idx_fault_case_memory_component` (`component`),
  KEY `idx_fault_case_memory_firmware` (`firmware_version`),
  KEY `idx_fault_case_memory_status` (`verification_status`),
  KEY `idx_fault_case_memory_created_at` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `retrieval_patches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback_id` INT NOT NULL,
  `scope` VARCHAR(32) NOT NULL DEFAULT 'feedback',
  `query_signature` VARCHAR(255) NOT NULL,
  `document_id` INT NOT NULL,
  `patch_type` VARCHAR(32) NOT NULL,
  `weight` FLOAT NOT NULL DEFAULT 0,
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `expires_at` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_retrieval_patches_feedback_id` (`feedback_id`),
  KEY `idx_retrieval_patches_scope` (`scope`),
  KEY `idx_retrieval_patches_query_signature` (`query_signature`),
  KEY `idx_retrieval_patches_document_id` (`document_id`),
  KEY `idx_retrieval_patches_patch_type` (`patch_type`),
  KEY `idx_retrieval_patches_status` (`status`),
  KEY `idx_retrieval_patches_expires_at` (`expires_at`),
  KEY `idx_retrieval_patches_scope_query_doc` (`scope`, `query_signature`, `document_id`)
);

CREATE TABLE IF NOT EXISTS `feedback_audit_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback_id` INT NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `before_state` MEDIUMTEXT NULL,
  `after_state` MEDIUMTEXT NULL,
  `reason` TEXT NULL,
  `actor` VARCHAR(64) NOT NULL DEFAULT 'system',
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_audit_logs_feedback_id` (`feedback_id`),
  KEY `idx_feedback_audit_logs_action` (`action`),
  KEY `idx_feedback_audit_logs_actor` (`actor`),
  KEY `idx_feedback_audit_logs_created_at` (`created_at`)
);
