import os
from pathlib import Path
from typing import List


def delete_file_if_exists(file_path: str) -> bool:
    if file_path and os.path.isfile(file_path):
        os.remove(file_path)
        return True
    return False


def delete_image_with_variants(image_path: str) -> List[str]:
    """Delete an image and the compressed variants generated by parsers/vector search."""
    path = Path(image_path)
    variants = [
        path,
        path.with_name(f"{path.stem}_compressed{path.suffix}"),
        path.with_name(f"{path.stem}_compressed_512{path.suffix}"),
        path.with_name(f"{path.stem}_compressed_768{path.suffix}"),
    ]

    deleted = []
    seen = set()
    for variant in variants:
        variant_str = str(variant)
        if variant_str in seen:
            continue
        seen.add(variant_str)
        if delete_file_if_exists(variant_str):
            deleted.append(variant_str)
    return deleted
