"""LoRA fine-tuning for the project's Visualized_BGE text encoder.

This script reads QA pairs generated by generate_qa_pairs.py. It trains the BGE
text encoder with in-batch contrastive learning:

    query = question
    positive = answer + source text

Only LoRA weights are trainable. The script can save both a small LoRA adapter
and a merged .pth file that can be used as MODEL_WEIGHT by this project.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import torch
import torch.nn.functional as F
from torch import nn
from torch.utils.data import DataLoader, Dataset


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from visual_bge.visual_bge.modeling import Visualized_BGE  # noqa: E402


@dataclass
class QAExample:
    question: str
    answer: str
    source_text: str
    source_file: str


@dataclass
class TrainingConfig:
    qa_data: str
    output_dir: str = ""
    model_name: str = "BAAI/bge-m3"
    model_weight: str = ""
    from_pretrained: str = ""
    positive_mode: str = "answer_source"
    max_source_chars: int = 2500
    query_max_len: int = 128
    passage_max_len: int = 512
    epochs: int = 1
    batch_size: int = 2
    gradient_accumulation_steps: int = 1
    learning_rate: float = 2e-4
    weight_decay: float = 0.0
    warmup_ratio: float = 0.05
    temperature: float = 0.02
    lora_rank: int = 8
    lora_alpha: float = 16.0
    lora_dropout: float = 0.05
    target_modules: str = "query,key,value"
    seed: int = 42
    logging_steps: int = 10
    save_merged_pth: bool = True
    merged_name: str = "Visualized_m3_lora_merged.pth"
    resume_adapter_dir: str = ""
    fp16: bool = True
    dry_run: bool = False


class QADataset(Dataset):
    def __init__(self, path: Path, positive_mode: str, max_source_chars: int) -> None:
        self.examples: list[QAExample] = []
        for item in read_qa_items(path):
            question = str(item.get("question", "")).strip()
            answer = str(item.get("answer") or item.get("ground_truth") or "").strip()
            source_text = str(item.get("source_text", "")).strip()
            source_file = str(item.get("source_file") or item.get("filename") or "").strip()
            if not question or not answer:
                continue
            if max_source_chars > 0 and len(source_text) > max_source_chars:
                source_text = source_text[:max_source_chars]
            positive = build_positive_text(answer, source_text, positive_mode)
            if positive:
                self.examples.append(QAExample(question, answer, positive, source_file))

        if not self.examples:
            raise ValueError(f"No valid QA examples found in {path}")

    def __len__(self) -> int:
        return len(self.examples)

    def __getitem__(self, index: int) -> QAExample:
        return self.examples[index]


def read_qa_items(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []
    if text.startswith("["):
        data = json.loads(text)
        return data if isinstance(data, list) else []

    items: list[dict] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            item = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(item, dict):
            items.append(item)
    return items


def build_positive_text(answer: str, source_text: str, mode: str) -> str:
    if mode == "answer":
        return answer
    if mode == "source":
        return source_text or answer
    if mode == "answer_source":
        if source_text:
            return f"{answer}\n\n依据片段：{source_text}"
        return answer
    raise ValueError(f"Unknown positive mode: {mode}")


def collate_examples(batch: list[QAExample]) -> dict[str, list[str]]:
    return {
        "questions": [item.question for item in batch],
        "positives": [item.source_text for item in batch],
        "source_files": [item.source_file for item in batch],
    }


class LoRALinear(nn.Module):
    def __init__(
        self,
        base_layer: nn.Linear,
        rank: int,
        alpha: float,
        dropout: float,
    ) -> None:
        super().__init__()
        if rank <= 0:
            raise ValueError("LoRA rank must be positive.")
        self.base_layer = base_layer
        self.rank = rank
        self.alpha = alpha
        self.scaling = alpha / rank
        self.dropout = nn.Dropout(dropout) if dropout > 0 else nn.Identity()

        self.lora_A = nn.Parameter(torch.empty(rank, base_layer.in_features, dtype=base_layer.weight.dtype))
        self.lora_B = nn.Parameter(torch.zeros(base_layer.out_features, rank, dtype=base_layer.weight.dtype))
        nn.init.kaiming_uniform_(self.lora_A, a=math.sqrt(5))

        for parameter in self.base_layer.parameters():
            parameter.requires_grad = False

    def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
        base_output = self.base_layer(input_tensor)
        lora_input = self.dropout(input_tensor)
        lora_output = F.linear(F.linear(lora_input, self.lora_A), self.lora_B) * self.scaling
        return base_output + lora_output

    def merged_linear(self) -> nn.Linear:
        merged = self.base_layer
        delta = torch.matmul(self.lora_B.data, self.lora_A.data) * self.scaling
        merged.weight.data = merged.weight.data + delta.to(device=merged.weight.device, dtype=merged.weight.dtype)
        return merged


def get_parent_module(root: nn.Module, module_name: str) -> tuple[nn.Module, str]:
    parts = module_name.split(".")
    parent = root
    for part in parts[:-1]:
        parent = getattr(parent, part)
    return parent, parts[-1]


def inject_lora_layers(
    root: nn.Module,
    target_modules: set[str],
    rank: int,
    alpha: float,
    dropout: float,
) -> list[str]:
    replaced: list[str] = []
    for name, module in list(root.named_modules()):
        if not name:
            continue
        short_name = name.rsplit(".", 1)[-1]
        if short_name not in target_modules:
            continue
        if not isinstance(module, nn.Linear):
            continue
        parent, child_name = get_parent_module(root, name)
        setattr(parent, child_name, LoRALinear(module, rank=rank, alpha=alpha, dropout=dropout))
        replaced.append(name)
    return replaced


def merge_lora_layers(root: nn.Module) -> int:
    merged_count = 0
    for name, module in list(root.named_modules()):
        if not isinstance(module, LoRALinear):
            continue
        parent, child_name = get_parent_module(root, name)
        setattr(parent, child_name, module.merged_linear())
        merged_count += 1
    return merged_count


def iter_lora_layers(root: nn.Module) -> Iterable[tuple[str, LoRALinear]]:
    for name, module in root.named_modules():
        if isinstance(module, LoRALinear):
            yield name, module


def freeze_all_parameters(model: nn.Module) -> None:
    for parameter in model.parameters():
        parameter.requires_grad = False


def trainable_parameters(model: nn.Module) -> list[nn.Parameter]:
    return [parameter for parameter in model.parameters() if parameter.requires_grad]


def count_parameters(model: nn.Module) -> tuple[int, int]:
    total = sum(parameter.numel() for parameter in model.parameters())
    trainable = sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad)
    return total, trainable


def save_lora_adapter(model: nn.Module, output_dir: Path, config: dict) -> None:
    adapter_dir = output_dir / "lora_adapter"
    adapter_dir.mkdir(parents=True, exist_ok=True)

    state: dict[str, torch.Tensor] = {}
    layer_names: list[str] = []
    for name, module in iter_lora_layers(model):
        layer_names.append(name)
        state[f"{name}.lora_A"] = module.lora_A.detach().cpu()
        state[f"{name}.lora_B"] = module.lora_B.detach().cpu()

    (adapter_dir / "adapter_config.json").write_text(
        json.dumps({**config, "lora_layers": layer_names}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    torch.save(state, adapter_dir / "adapter_model.pt")


def load_lora_adapter(model: nn.Module, adapter_dir: Path) -> None:
    state_path = adapter_dir / "adapter_model.pt"
    if not state_path.exists():
        raise FileNotFoundError(f"LoRA adapter not found: {state_path}")
    state = torch.load(state_path, map_location="cpu")
    layer_map = dict(iter_lora_layers(model))
    missing: list[str] = []
    for name, module in layer_map.items():
        key_a = f"{name}.lora_A"
        key_b = f"{name}.lora_B"
        if key_a not in state or key_b not in state:
            missing.append(name)
            continue
        module.lora_A.data.copy_(state[key_a].to(device=module.lora_A.device, dtype=module.lora_A.dtype))
        module.lora_B.data.copy_(state[key_b].to(device=module.lora_B.device, dtype=module.lora_B.dtype))
    if missing:
        print(f"[WARN] adapter missing {len(missing)} LoRA layers.")


def save_training_config(output_dir: Path, args: TrainingConfig, lora_layers: list[str]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    config = vars(args).copy()
    config["lora_layers"] = lora_layers
    (output_dir / "training_config.json").write_text(
        json.dumps(config, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def tokenize(tokenizer, texts: list[str], max_length: int, device: torch.device) -> dict[str, torch.Tensor]:
    batch = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    return {key: value.to(device) for key, value in batch.items()}


def set_hf_cache_from_env() -> None:
    model_cache = os.getenv("MODEL_DOWNLOAD_URL")
    if model_cache and "HF_HOME" not in os.environ:
        os.environ["HF_HOME"] = model_cache


def resolve_path(value: str | Path) -> Path:
    return Path(value).expanduser().resolve()


def default_output_for_qa_data(qa_path: Path) -> Path:
    return qa_path.parent / "output"


def resolve_default_model_weight() -> str:
    return str(resolve_path(os.getenv("MODEL_WEIGHT", str(PROJECT_ROOT / "bge" / "Visualized_m3.pth"))))


def parse_target_modules(value: str) -> set[str]:
    return {item.strip() for item in value.split(",") if item.strip()}


def run_training(args: TrainingConfig) -> int:
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)

    qa_path = resolve_path(args.qa_data)
    output_dir = resolve_path(args.output_dir) if args.output_dir else default_output_for_qa_data(qa_path)
    args.qa_data = str(qa_path)
    args.output_dir = str(output_dir)
    dataset = QADataset(qa_path, positive_mode=args.positive_mode, max_source_chars=args.max_source_chars)
    print(f"Loaded {len(dataset)} QA examples from {qa_path}")
    print("Sample question:", dataset[0].question)
    print("Sample positive:", dataset[0].source_text[:300].replace("\n", " "))

    if args.dry_run:
        return 0

    set_hf_cache_from_env()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    if not args.model_weight:
        args.model_weight = resolve_default_model_weight()
    model_weight = str(resolve_path(args.model_weight))
    args.model_weight = model_weight
    if not Path(model_weight).exists():
        raise FileNotFoundError(f"MODEL_WEIGHT not found: {model_weight}")

    from_pretrained = args.from_pretrained.strip() or None
    model = Visualized_BGE(
        model_name_bge=args.model_name,
        model_weight=model_weight,
        from_pretrained=from_pretrained,
        temperature=args.temperature,
    )
    model.to(device)

    freeze_all_parameters(model)
    target_modules = parse_target_modules(args.target_modules)
    lora_layers = inject_lora_layers(
        model.bge_encoder,
        target_modules=target_modules,
        rank=args.lora_rank,
        alpha=args.lora_alpha,
        dropout=args.lora_dropout,
    )
    if not lora_layers:
        raise RuntimeError(
            f"No Linear layers matched --target-modules={args.target_modules}. "
            "Try --target-modules query,key,value,dense"
        )
    model.to(device)

    if args.resume_adapter_dir:
        resume_adapter_dir = resolve_path(args.resume_adapter_dir)
        args.resume_adapter_dir = str(resume_adapter_dir)
        load_lora_adapter(model, resume_adapter_dir)

    total, trainable = count_parameters(model)
    print(f"Injected LoRA into {len(lora_layers)} layers: {', '.join(sorted(set(name.rsplit('.', 1)[-1] for name in lora_layers)))}")
    print(f"Parameters: trainable={trainable:,} / total={total:,} ({trainable / total:.4%})")

    save_training_config(output_dir, args, lora_layers)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        collate_fn=collate_examples,
        drop_last=False,
    )

    optimizer = torch.optim.AdamW(trainable_parameters(model), lr=args.learning_rate, weight_decay=args.weight_decay)
    total_update_steps = max(1, math.ceil(len(loader) * args.epochs / args.gradient_accumulation_steps))
    warmup_steps = int(total_update_steps * args.warmup_ratio)

    def lr_lambda(step: int) -> float:
        if warmup_steps > 0 and step < warmup_steps:
            return float(step + 1) / float(max(1, warmup_steps))
        progress = float(step - warmup_steps) / float(max(1, total_update_steps - warmup_steps))
        return max(0.0, 1.0 - progress)

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
    scaler = torch.cuda.amp.GradScaler(enabled=args.fp16 and device.type == "cuda")
    loss_log_path = output_dir / "train_loss.jsonl"
    loss_log_path.parent.mkdir(parents=True, exist_ok=True)

    global_step = 0
    optimizer.zero_grad(set_to_none=True)
    model.train()

    with loss_log_path.open("a", encoding="utf-8") as loss_writer:
        for epoch in range(1, args.epochs + 1):
            running_loss = 0.0
            seen_batches = 0
            for batch_index, batch in enumerate(loader, start=1):
                batch_size = len(batch["questions"])
                if batch_size < 2:
                    continue

                query_tokens = tokenize(model.tokenizer, batch["questions"], args.query_max_len, device)
                positive_tokens = tokenize(model.tokenizer, batch["positives"], args.passage_max_len, device)

                with torch.cuda.amp.autocast(enabled=args.fp16 and device.type == "cuda"):
                    query_reps = model.encode_text(query_tokens)
                    positive_reps = model.encode_text(positive_tokens)
                    scores = torch.matmul(query_reps, positive_reps.transpose(0, 1)) / args.temperature
                    labels = torch.arange(scores.size(0), device=device)
                    loss = F.cross_entropy(scores, labels)
                    loss_for_backward = loss / args.gradient_accumulation_steps

                scaler.scale(loss_for_backward).backward()
                running_loss += loss.item()
                seen_batches += 1

                should_step = batch_index % args.gradient_accumulation_steps == 0 or batch_index == len(loader)
                if should_step:
                    scaler.unscale_(optimizer)
                    torch.nn.utils.clip_grad_norm_(trainable_parameters(model), max_norm=1.0)
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)
                    scheduler.step()
                    global_step += 1

                    record = {
                        "epoch": epoch,
                        "step": global_step,
                        "loss": loss.item(),
                        "lr": scheduler.get_last_lr()[0],
                    }
                    loss_writer.write(json.dumps(record, ensure_ascii=False) + "\n")
                    loss_writer.flush()

                    if global_step % args.logging_steps == 0:
                        avg_loss = running_loss / max(1, seen_batches)
                        print(f"epoch={epoch} step={global_step}/{total_update_steps} loss={avg_loss:.6f} lr={scheduler.get_last_lr()[0]:.2e}")
                        running_loss = 0.0
                        seen_batches = 0

            save_lora_adapter(
                model,
                output_dir,
                config={
                    "model_name": args.model_name,
                    "base_model_weight": model_weight,
                    "rank": args.lora_rank,
                    "alpha": args.lora_alpha,
                    "dropout": args.lora_dropout,
                    "target_modules": sorted(target_modules),
                    "positive_mode": args.positive_mode,
                },
            )
            print(f"Saved LoRA adapter after epoch {epoch}: {output_dir / 'lora_adapter'}")

    if args.save_merged_pth:
        merged_count = merge_lora_layers(model)
        merged_path = output_dir / args.merged_name
        torch.save(model.state_dict(), merged_path)
        print(f"Merged {merged_count} LoRA layers into full model weight: {merged_path}")

    print("Done.")
    return 0


if __name__ == "__main__":
    QA_DATA_JSON = r"C:\Users\exile\Desktop\data\source_documents\source_documents\data1.json"
    OUTPUT_DIR = r""

    config = TrainingConfig(
        qa_data=QA_DATA_JSON,
        output_dir=OUTPUT_DIR,
        model_weight=resolve_default_model_weight(),
    )
    raise SystemExit(run_training(config))
